fix:github deployment pipeline

diff --git a/.github/workflows/main-deploy.yml b/.github/workflows/main-deploy.yml
--- a/.github/workflows/main-deploy.yml
+++ b/.github/workflows/main-deploy.yml
@@ -1,5 +1,5 @@
-# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 name: Build, Push Docker Image, Deploy to EC2
+
 on:
   #trigger on push on "deploy" branch
   push:
@@ -36,19 +36,16 @@ jobs:
     runs-on: ubuntu-latest      
 
     steps:
-  
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Fetching full history so we can checkout any commit
+            fetch-depth: 0  # Fetching full history so we can checkout any commit
 
-      
       - name: Checkout specific commit if git_hash is provided
         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.git_hash != '' }}
         run: |
           git checkout ${{ github.event.inputs.git_hash }}
 
-        
       - name: Initialize Global Log File
         run: |
           echo "LOG_FILE=workflow.log" >> $GITHUB_ENV
@@ -66,12 +63,10 @@ jobs:
             fi
           }
           check "${{ secrets.DOMAIN_NAME_STAG }}" "DOMAIN_NAME_STAG"
-          check "${{ secrets.NAMESERVERS_STAG }}" "NAMESERVERS_STAG"
           check "${{ secrets.EC2_HOST_STAG }}" "EC2_HOST_STAG"
           check "${{ secrets.EC2_SSH_KEY_STAG }}" "EC2_SSH_KEY_STAG"
           check "${{ secrets.DATABASE_DIRECT_URL_STAG}}" "DATABASE_DIRECT_URL_STAG"
           check "${{ secrets.DOMAIN_NAME_PROD }}" "DOMAIN_NAME_PROD"
-          check "${{ secrets.NAMESERVERS_PROD }}" "NAMESERVERS_PROD"
           check "${{ secrets.EC2_HOST_PROD }}" "EC2_HOST_PROD"
           check "${{ secrets.EC2_SSH_KEY_PROD }}" "EC2_SSH_KEY_PROD"
           check "${{ secrets.DATABASE_DIRECT_URL_PROD}}" "DATABASE_DIRECT_URL_PROD"
@@ -120,7 +115,19 @@ jobs:
           check "${{ secrets.NEXT_PUBLIC_POSTHOG_KEY_PROD }}" "NEXT_PUBLIC_POSTHOG_KEY_PROD"
           check "${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}" "NEXT_PUBLIC_POSTHOG_HOST"
           
-      
+      # SETTING NECESSARY ENV VARIABLES
+      - name: Extract Git commit hash
+        if: ${{ steps.check_required_secrets_status.outputs.passed != 'failure' }}
+        id: hash
+        run: |
+          if [ -n "${{ github.event.inputs.git_hash }}" ]; then
+            hash="${{ github.event.inputs.git_hash }}"
+            echo "[INFO]: ↩️ Rollback Step" >> "$LOG_FILE"
+          else
+            hash="$(git rev-parse HEAD)"
+            echo "[INFO]: 🆕 New Deployment Step" >> "$LOG_FILE"
+          fi
+          echo "GIT_HASH=$hash" >> $GITHUB_OUTPUT
         
       # BUILDING AND PUSHING DOCKER IMAGE
       - name: Set up Docker Buildx
@@ -170,24 +177,11 @@ jobs:
           BRANCH_NAME="${{ github.event.inputs.branch != '' && github.event.inputs.branch || github.ref_name }}"
           echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
 
-      - name: Extract Git commit hash
-        id: hash
-        run: |
-          if [ -n "${{ github.event.inputs.git_hash }}" ]; then
-            hash="${{ github.event.inputs.git_hash }}"
-            echo "[INFO]: ↩️ Old Deployment Action" >> "$LOG_FILE"
-          else
-            hash="$(git rev-parse HEAD)"
-            echo "[INFO]: 🆕 New Deployment Action" >> "$LOG_FILE"
-          fi
-          echo "GIT_HASH=$hash" >> $GITHUB_OUTPUT
-
-      - name: Set dynamic key values for  DOMAIN_NAME , NAMESERVERS ,EC2_HOST ,EC2_SSH_KEY , DATABASE_URL
+      - name: Set dynamic key values based on deployment environment
         id : key_values
         run: | 
           if [ "${{ steps.set_branch.outputs.branch_name }}" == "main" ]; then
             echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME_PROD }}" >> $GITHUB_OUTPUT
-            echo "NAMESERVERS=${{ secrets.NAMESERVERS_PROD }}" >> $GITHUB_OUTPUT
             echo "EC2_HOST=${{ secrets.EC2_HOST_PROD }}" >> $GITHUB_OUTPUT
             echo "EC2_SSH_KEY<<EOF" >> $GITHUB_OUTPUT
             echo "${{ secrets.EC2_SSH_KEY_PROD }}" >> $GITHUB_OUTPUT
@@ -204,7 +198,6 @@ jobs:
             echo "NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY_PROD }}" >> $GITHUB_OUTPUT
           else
             echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME_STAG }}" >> $GITHUB_OUTPUT
-            echo "NAMESERVERS=${{ secrets.NAMESERVERS_STAG }}" >> $GITHUB_OUTPUT
             echo "EC2_HOST=${{ secrets.EC2_HOST_STAG }}" >> $GITHUB_OUTPUT
             echo "EC2_SSH_KEY<<EOF" >> $GITHUB_OUTPUT
             echo "${{ secrets.EC2_SSH_KEY_STAG }}" >> $GITHUB_OUTPUT
@@ -229,7 +222,7 @@ jobs:
         with:
           region: ${{ secrets.AWS_REGION }}
           repository-name: ${{ steps.key_values.outputs.REPO_NAME }}
-          image-tag: ${{ steps.hash.outputs.GIT_HASH }}
+          image-tag: ${{ steps.hash.outputs.git_hash }}
           access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
@@ -256,9 +249,15 @@ jobs:
           platforms: linux/amd64
           push: true
           tags: |
-            ${{ steps.login-ecr.outputs.registry }}/${{ steps.key_values.outputs.REPO_NAME }}:${{ steps.hash.outputs.GIT_HASH }}
+            ${{ steps.login-ecr.outputs.registry }}/${{ steps.key_values.outputs.REPO_NAME }}:${{ steps.hash.outputs.git_hash }}
             ${{ steps.login-ecr.outputs.registry }}/${{ steps.key_values.outputs.REPO_NAME }}:latest
           build-args: |
+            CALENDSO_ENCRYPTION_KEY=${{ secrets.CALENDSO_ENCRYPTION_KEY }}
+            NEXT_PUBLIC_WEBAPP_URL=${{ format('https://app.{0}', steps.key_values.outputs.DOMAIN_NAME) }}
+            NEXT_PUBLIC_WEBSITE_URL=${{ format('https://{0}', steps.key_values.outputs.DOMAIN_NAME) }}
+            NEXT_PUBLIC_API_V2_URL=${{ secrets.NEXT_PUBLIC_API_V2_URL }}
+            NEXT_PUBLIC_EMBED_LIB_URL=${{ format('https://{0}/embed/embed.js', steps.key_values.outputs.DOMAIN_NAME) }}
+            NEXT_PUBLIC_ONEHASH_URL=${{ secrets.NEXT_PUBLIC_ONEHASH_URL }}
             NEXTAUTH_URL=${{ steps.key_values.outputs.DOMAIN_NAME }}
             NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
             NEXT_PUBLIC_SENDGRID_SENDER_NAME=${{ secrets.BRAND_NAME }}
@@ -287,9 +286,6 @@ jobs:
             NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS=${{ secrets.NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS }}
             NEXT_PUBLIC_POSTHOG_HOST=${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
             NEXT_PUBLIC_POSTHOG_KEY=${{ steps.key_values.outputs.NEXT_PUBLIC_POSTHOG_KEY }}
-            CALENDSO_ENCRYPTION_KEY=${{ secrets.CALENDSO_ENCRYPTION_KEY }}
-            NEXT_PUBLIC_WEBAPP_URL=${{ format('https://{0}', steps.key_values.outputs.DOMAIN_NAME) }}
-            NEXT_PUBLIC_API_V2_URL=${{ secrets.NEXT_PUBLIC_API_V2_URL }}
 
       - name: Check Docker build status
         shell: bash
@@ -308,7 +304,7 @@ jobs:
         uses: appleboy/ssh-action@v0.1.10
         id: ssh_deploy
         env:
-          NAMESERVERS: ${{ steps.key_values.outputs.NAMESERVERS }}
+          DOMAIN_NAME: ${{ steps.key_values.outputs.DOMAIN_NAME }}
           EC2_HOST: ${{ steps.key_values.outputs.EC2_HOST }}
           EC2_SSH_KEY: ${{ steps.key_values.outputs.EC2_SSH_KEY }}
           REPO_URL: ${{secrets.REPO_URL}}
@@ -320,14 +316,14 @@ jobs:
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
           REPO_NAME: ${{ steps.key_values.outputs.REPO_NAME }}
           CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
-          GIT_HASH: ${{ steps.hash.outputs.GIT_HASH }}
+          GIT_HASH: ${{ steps.hash.outputs.git_hash }}
           IS_ROLLBACK: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.git_hash != '' }}
         with:
           host: ${{ env.EC2_HOST }}
           username: "onehash"
           key: ${{ env.EC2_SSH_KEY }}
           command_timeout: 1500s # 25 minutes
-          envs: NAMESERVERS, AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_ACCOUNT_ID, AWS_ACCOUNT_ID, REPO_NAME, REPO_URL, BRANCH_NAME, CERTBOT_EMAIL, GIT_HASH ,IS_ROLLBACK
+          envs:  AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_ACCOUNT_ID, AWS_ACCOUNT_ID, REPO_NAME, REPO_URL, BRANCH_NAME, CERTBOT_EMAIL, GIT_HASH ,IS_ROLLBACK ,DOMAIN_NAME
           script: |
             #!/bin/bash
 
@@ -475,9 +471,29 @@ jobs:
               exit 1
             fi
 
-            # Stop and remove any existing container with the same name
-            docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
-            log_message "INFO" "Removed any existing container with name $CONTAINER_NAME"
+            #Check if we have enough space to start a new container in GB
+            AVAILABLE_SPACE=$(df -BG / | tail -1 | awk '{print $4}' | sed 's/G//')
+
+            # Log available space
+            log_message "INFO" "Available disk space: ${AVAILABLE_SPACE}GB"
+
+            #If available space is less than 10GB, lets try to prune unused Docker images and containers
+            if [ "$AVAILABLE_SPACE" -lt 10 ]; then 
+              log_message "WARN" "⚠️ Available disk space is low: ${AVAILABLE_SPACE}GB. Pruning unused Docker images and containers older than 72 hours."
+              if ! exec_command "Docker system prune" "docker system prune -af --volumes && docker volume prune -af"; then
+                log_message "ERROR" "❌ Failed to prune unused Docker images and containers"
+                exit 1
+              fi
+              AVAILABLE_SPACE=$(df -BG / | tail -1 | awk '{print $4}' | sed 's/G//')
+              if [ "$AVAILABLE_SPACE" -lt 10 ]; then
+                log_message "ERROR" "❌ Still insufficient disk space after pruning: ${AVAILABLE_SPACE}GB. Aborting deployment."
+                exit 1
+              else
+                log_message "INFO" "✅ Disk space after pruning: ${AVAILABLE_SPACE}GB"
+              fi
+            else
+              log_message "INFO" "✅ Sufficient disk space available: ${AVAILABLE_SPACE}GB"
+            fi
 
             #Running container
             log_message "INFO" "Starting Docker container '$CONTAINER_NAME' on port $NEW_PORT"
@@ -552,7 +568,7 @@ jobs:
               exit 1
             fi
 
-            if ! exec_command "Replace DOMAIN" "sudo sed -i \"s/DOMAIN_PLACEHOLDER/$NAMESERVERS/g\" \"$NGINX_CONF_PATH\""; then
+            if ! exec_command "Replace DOMAIN" "sudo sed -i \"s/DOMAIN_PLACEHOLDER/$DOMAIN_NAME/g\" \"$NGINX_CONF_PATH\""; then
               exit 1
             fi
 
@@ -570,9 +586,9 @@ jobs:
             # fi
 
             # SSL Certificate with certbot
-            log_message "INFO" "Generating SSL cert for $NAMESERVERS"
+            log_message "INFO" "Generating SSL cert for $DOMAIN_NAME"
             # Add a timeout to certbot to prevent hanging
-            if ! exec_command "Certbot SSL" "timeout 300s sudo certbot certonly -a dns-multi --dns-multi-credentials=/etc/letsencrypt/dns-multi.ini -d \"*.${NAMESERVERS}\" -d \"${NAMESERVERS}\" -m \"${CERTBOT_EMAIL}\" --non-interactive --agree-tos"; then
+            if ! exec_command "Certbot SSL" "timeout 300s sudo certbot certonly -a dns-multi --dns-multi-credentials=/etc/letsencrypt/dns-multi.ini -d \"*.${DOMAIN_NAME}\" -d \"${DOMAIN_NAME}\" -m \"${CERTBOT_EMAIL}\" --non-interactive --agree-tos"; then
               log_message "WARN" "⚠️ Certbot SSL generation may have issues, but continuing with deployment"
             fi
 
